tg:
  bot:
    name: "yunxiao_bot"
    token: "***"
wallhaven:
  key: "***"
yuapi:
  client:
    access-key: "***"
    secret-key: "***"
spring:
  profiles:
    active: dev
  main:
    web-application-type: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "***"
    password: "***"
    url: jdbc:mysql://localhost:3306/tg-yunxiao-bot?characterEncoding=utf-8&useSSL=false